### ISSUE TITLE
Regarding pretraining time

### ISSUE THREAD

**Issue by juhongm999** [dandelin/ViLT#16]
First of all, thanks for great work.
Can you tell us how long the pretraining took on your machine with 64 V100s ?
Thank you in advance

**Comment by dandelin** [comment]
Hi, @juhongm999 

I've shared 100k tensorboard log here -> https://github.com/dandelin/ViLT/issues/12#issuecomment-859458931 

You can check the training time there 😃

**Comment by juhongm999** [comment]
Thank you for quick reply!
