### ISSUE TITLE
Time cost when fine-tuning on COCO-irtr dataset

### ISSUE THREAD

**Issue by simplelifetime** [dandelin/ViLT#29]
Hi, Thanks for your fantastic work
  I've been trying to reproduce the result on fine-tuning on pre-trained model.It takes me only about 6 hours to fine-tune on VQAV2 dataset.But when I try to fine-tune on the COCO dataset,It took me about 20 hours to run only 1 epoch,I wonder if It's the corrent result.
  Also,I find that when I finish one epoch fine-tuning on COCO dataset,It didn't automatically save the model.Is there a problem with my setting?
  My experiement was ran on 8 V100 GPUs.

**Comment by dandelin** [comment]
Hi @simplelifetime,

The reason why IRTR tasks take so long is that it requires every pair to be passed through the transformer when validation to get the image-text matching score.
It causes drastically longer evaluation time compared to those require simple dot product to get the score.

You can reduce the overall fine-tuning time by simply not doing evaluation for every epoch.
Pass `val_check_interval >= float(epochs)` argument to `pl.Trainer`'s init function in `run.py` will do the job.

**Comment by simplelifetime** [comment]
Thank you for your reply!That really helps solve my problem.
