### ISSUE TITLE
Is it necessary to manually add the sampler in the dataloader?

### ISSUE THREAD

**Issue by zhiqiangdon** [dandelin/ViLT#34]
Hi,

Is it necessary to manually add the Pytorch's DistributedSampler in the dataloader?

https://github.com/dandelin/ViLT/blob/master/vilt/datamodules/multitask_datamodule.py#L46

It seems that Pytorch Lightning automatically uses the Pytorch's DistributedSampler.

**Comment by dandelin** [comment]
Hi @zhiqiangdon,

It is legacy code, it's perfectly fine to use `pytorch_lightning`'s automatically handled `DistributedSampler`.

**Comment by zhiqiangdon** [comment]
Got it. Thanks!
