### ISSUE TITLE
Add ViLT to HuggingFace Transformers

### ISSUE THREAD

**Issue by NielsRogge** [dandelin/ViLT#36]
Hi,

I've been reading the ViLT paper and was impressed by the simplicity, as it only adds text embeddings to a ViT.

As ViT is already available in HuggingFace Transformers, adding ViLT should be relatively easy.

I've currently implemented the model (see [here](https://github.com/NielsRogge/transformers/tree/modeling_vilt/src/transformers/models/vilt) for my current implementation). It includes a conversion script (`convert_vilt_original_to_pytorch.py`) to convert the weights from this repository (the PyTorch Lightning module) to its HuggingFace counterpart, for all models (base one + the ones with a head on top).

However, I'm facing some issues when performing a forward pass with the original implementation in Google Colab (when just doing `pip install -r requirements.txt` and running the `demo_vqa.py` script, you get the following):

```
Traceback (most recent call last):
  File "demo_vqa.py", line 17, in <module>
    from vilt.modules import ViLTransformerSS
  File "/content/ViLT/vilt/modules/__init__.py", line 1, in <module>
    from .vilt_module import ViLTransformerSS
  File "/content/ViLT/vilt/modules/vilt_module.py", line 3, in <module>
    import pytorch_lightning as pl
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/__init__.py", line 62, in <module>
    from pytorch_lightning import metrics
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/metrics/__init__.py", line 14, in <module>
    from pytorch_lightning.metrics.metric import Metric
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/metrics/metric.py", line 23, in <module>
    from pytorch_lightning.metrics.utils import _flatten, dim_zero_cat, dim_zero_mean, dim_zero_sum
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/metrics/utils.py", line 18, in <module>
    from pytorch_lightning.utilities import rank_zero_warn
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/utilities/__init__.py", line 24, in <module>
    from pytorch_lightning.utilities.apply_func import move_data_to_device
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/utilities/apply_func.py", line 25, in <module>
    from torchtext.data import Batch
ImportError: cannot import name 'Batch' from 'torchtext.data' (/usr/local/lib/python3.7/dist-packages/torchtext/data/__init__.py)

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True
```

Upgrading PyTorch Lightning to the latest version also returns an error:

```
Traceback (most recent call last):
  File "demo_vqa.py", line 17, in <module>
    from vilt.modules import ViLTransformerSS
  File "/content/ViLT/vilt/modules/__init__.py", line 1, in <module>
    from .vilt_module import ViLTransformerSS
  File "/content/ViLT/vilt/modules/vilt_module.py", line 7, in <module>
    from vilt.modules import heads, objectives, vilt_utils
  File "/content/ViLT/vilt/modules/vilt_utils.py", line 11, in <module>
    from vilt.gadgets.my_metrics import Accuracy, VQAScore, Scalar
  File "/content/ViLT/vilt/gadgets/my_metrics.py", line 2, in <module>
    from pytorch_lightning.metrics import Metric
ModuleNotFoundError: No module named 'pytorch_lightning.metrics'
```
As PL deprecated the metrics module. 

Are you able to provide a simple Colab notebook to perform inference on an image+text pair?

Thanks!

**Comment by NielsRogge** [comment]
Update:

seems to work when doing `pip install pytorch_lightning==1.4.8`

**Comment by dandelin** [comment]
Thank you for your efforts @NielsRogge 

I would be grateful if ViLT is implemented in Huggingface Transformers as it is a widely used library among the community.

Please keep me in the loop and use this issue for any question that pops up.

**Comment by NielsRogge** [comment]
Hi,

I've got an inference notebook working: https://colab.research.google.com/drive/1bFekGSb4bvN1fJToo-EiQZi-jefE8HSU?usp=sharing

The VQAv2 checkpoint is on the hub: https://huggingface.co/nielsr/vilt-base-finetuned-vqa. As you can see, currently the model card needs to be filled in. Also, I've stored the model under my personal name, but maybe it makes more sense for you to host them under either your personal account on the hub, or an organization (like NAVER AI Labs). People can then load the checkpoint using .from_pretrained("naver/vilt-base-finetuned-vqa").

Note that you can choose the naming of the models to whatever you like.

Are you interested in creating an user/organization on the hub? This will also give you write access to all these models, allowing you to easily edit them, have versioning, etc.

**Comment by dandelin** [comment]
Hi @NielsRogge 

It will be my pleasure if you allow me to host the model you converted.
I just got signed up on the hub (https://huggingface.co/dandelin).
Since I never used the hub, could you guide me on how to host the model by myself?
Maybe clone your model and re-upload it?

**Comment by NielsRogge** [comment]
Hi,

Awesome! So adding a model can be done by clicking on the top right (when you're signed in) => new model, and then you can choose to either host it under your own name or an organization (so if you have multiple members in your team, it might make sense to create an organization). 

Are you part of Naver Labs? https://huggingface.co/naver Then it might make sense to add you to that organization, and host the model weights under that organization (whatever you prefer).

I can transfer the weights for you.

**Comment by dandelin** [comment]
@NielsRogge 

This project is done while I was at Kakao corporation, so the ownership is kind of in the gray zone.
So I would like to host it under my account (dandelin).
Thank you so much!

**Comment by NielsRogge** [comment]
Ok :) can you create a new model on the hub? Then I'll upload the weights to your repo.

**Comment by NielsRogge** [comment]
Ok the weights are transferred :) 

So you would like to work on this further? Great! I could assist you if you want, the modeling is mostly done, however I still need to add the possibility for training all models. Most models in Transformers just take a `labels` argument for computing a loss, however I saw that for VQAv2 one needs both `labels` and `scores`, and a binary cross-entropy is used, I wonder why? Haven't looked into that dataset before, but it would be great to get a single example (because we will also need that for the tests). 

If you're interested, I can set up a Slack channel to discuss this further.

**Comment by NielsRogge** [comment]
Hi @dandelin,

I'm actually finished with most models, however it seems like the image embeddings are not deterministic, even when setting max_image_length = -1. It seems that a multinomial distribution is used to sample, as seen [here](https://github.com/dandelin/ViLT/blob/3db8b5035464afee84d951bf6322e1b27f1d072d/vilt/modules/vision_transformer.py#L630-L642).

Can you clarify this? Is it possible to get deterministic image embeddings?

Thank you!

**Comment by dandelin** [comment]
Hi @NielsRogge 

Sorry for the late reply.

Sure, you can get deterministic embeddings. The purpose of [these lines](https://github.com/dandelin/ViLT/blob/3db8b5035464afee84d951bf6322e1b27f1d072d/vilt/modules/vision_transformer.py#L602-L648) is to batch variously-sized images by padding them. The whole lines from L602 to L648 can simply be ignored.

Though in that case, you should pass the model equally-sized images or a single image.

Thank you for your efforts.

**Comment by seifmaged31** [comment]
> Hi,
> 
> I've got an inference notebook working: https://colab.research.google.com/drive/1bFekGSb4bvN1fJToo-EiQZi-jefE8HSU?usp=sharing
> 
Thank you for you contribution @NielsRogge, but the demo doesn't seem to be working in my case.

`ImportError                               Traceback (most recent call last)
<ipython-input-5-ba68cf17dcea> in <module>()
----> 1 from transformers import ViltForVisualQuestionAnswering
      2 
      3 model = ViltForVisualQuestionAnswering.from_pretrained("nielsr/vilt-base-finetuned-vqa")

ImportError: cannot import name 'ViltForVisualQuestionAnswering' from 'transformers' (/usr/local/lib/python3.7/dist-packages/transformers/__init__.py)` 


Your help would be much appreciated, I am new in deep learning :)

**Comment by NielsRogge** [comment]
Hi,

ViLT has been added some time ago to Huggingface Transformers! 🥳 

Docs can be found here: https://huggingface.co/docs/transformers/main/en/model_doc/vilt

Demo notebooks can be found [here](https://github.com/NielsRogge/Transformers-Tutorials/tree/master/ViLT).

All models can be found on the [hub](https://huggingface.co/models?other=vilt).
