### ISSUE TITLE
Why is answers set to 0 for irtr even for the positive case?

### ISSUE THREAD

**Issue by TheShadow29** [dandelin/ViLT#63]
Hello, thanks for the amazing repository. If I understand correct, for IRTR, `answer` should be 1 for the first element which is true, and 0 for the remaining false texts (https://github.com/dandelin/ViLT/blob/master/vilt/modules/objectives.py#L429)

But in the code, it sets all of them including the positive sample to be zero. Am I missing something here? Thanks!

**Comment by TheShadow29** [comment]
Whoops, I just realized it is cross entropy, not binary cross entropy. Please ignore the issue.

**Comment by mactavish91** [comment]
@TheShadow29  So why is answers always set to 0? All tags are 0.

**Comment by TheShadow29** [comment]
@mactavish91 first ITM is true, others are false. So targets are all 0.
